### PR TITLE
Update sk.json

### PR DESCRIPTION
**Pull request by misa1515**

### CODE REVIEW

**Comment by TechHummel** [comment]
Hi and thanks a lot for your contribution! 👍 
Did you verify that the translations work correctly in home assistant? I did notice that the setup and configuration translations weren't working correctly for me any more - so it would be great to know if this is the json structure we need to make everything working again 😄

**Comment by TechHummel** [comment]
https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/pull/168

**Comment by misa1515** [comment]
How may I run pre-commit?

**Comment by TechHummel** [comment]
Don't worry, I merged your changes, thank you!

**Comment by misa1515** [comment]
@TechHummel you merged it, but still not found sk.json (slovak) in code.
May you check it, please?

**Comment by TechHummel** [comment]
You are right! Sorry about that 😇

**Pull request closed without merging**
